// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcwakwnapsdaebiydfkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjd2Frd25hcHNkYWViaXlkZmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzI1NTUsImV4cCI6MjA2NzgwODU1NX0.g72ZSbAuMwFiBmj1rqSXtz9P-0VC9uK0eW9C-Mu5zHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});